### ISSUE TITLE
Add negative tests to ensure authentication is enforced

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#1005]
Validate that mTLS works as expected by sending invalid certs, no certs, etc and expecting an error.

**Comment by wattli** [comment]
Is there any positive tests that I can take a look?

**Comment by wattli** [comment]
never mind, found https://github.com/istio/pilot/commit/eba973b40e6445d951473415c562cb8b09cfb2fd

**Comment by kyessenov** [comment]
I think @wattli is on it.

**Comment by wattli** [comment]
Yes, i am working on it now

**Comment by kyessenov** [comment]
Raising priority since a security bug slipped once already.

**Comment by wattli** [comment]
try to do it by next week.

**Comment by wattli** [comment]
https://github.com/istio/pilot/pull/1090 is fixing this.
