### ISSUE TITLE
Expose websocket routes

### ISSUE THREAD

**Issue by rshriram** [istio/pilot#1006]
Envoy has support for WebSockets now (https://github.com/lyft/envoy/pull/1274). However, routes that support WebSockets must be explicitly marked using the `use_websocket` option. 

This has two implications:
* For a HTTP port (say 80) on a service, that has several routes (plain http and websocket) (/foo, /bar and /websocket), the user needs to mark websocket enabled routes explicitly through route rules.
* For services that have websocket on a dedicated port (i.e., no http routes), the user could name the port as a websocket port (like http, grpc, etc.). This would mean that all routes on that port are websocket routes (preventing normal http connections from working.

WE could start with option 1 and then see if it makes sense to introduce a new port name/type (Websocket) as I feel that option 2 is redundant.
cc @kyessenov

**Comment by kyessenov** [comment]
1) makes more sense for ingress while 2) is more in-line how we use services in-cluster. I think we might need both options, but for different proxies.

**Comment by rshriram** [comment]
(1) also makes sense for in-cluster proxies, if there are multiple services on same port. Or, if a given service has HTTP routes and one or more websocket routes. (2) is more of a coarse grained solution.

**Comment by rshriram** [comment]
fixed by #1094
