### ISSUE TITLE
istioctl version issues: should output its own version even without ~/.kube/config

### ISSUE THREAD

**Issue by ldemailly** [istio/pilot#1018]
- [x] istioctl version errors out without a ~/.kube/config it should not
- [ ] after printing its own version it should try to print kubernetes, api server, pilot and mixer versions (would serve as a basic check those exist too)

cc @sebastienvas who encountered the first issue

**Comment by cmluciano** [comment]
I'm trying to figure out where this dep comes from. Is this b/c we parse the version from kube-inject?

**Comment by ldemailly** [comment]
my guess it's initialization order, it does k8s stuff before it gets to just output version

**Comment by ldemailly** [comment]
we don't parse kube version anymore but we should (after we dumped the internal/istio ones)

**Comment by kyessenov** [comment]
without istioctl, this is no longer needed.

**Comment by ldemailly** [comment]
We have istioctl in 0.2

**Comment by rshriram** [comment]
We are not going to get rid of istioctl even if we have a kube based config
store in mesos or VMs. It's silly to expect people to use kubectl if they
have not installed kubectl. The fact that we are using kubernetes as config
server is implementation detail and user shouldn't care.
-- 

~shriram

**Comment by ldemailly** [comment]
fixing this as part of my other PR

**Comment by ldemailly** [comment]
going to close this one as I fixed 1/2 of it and make a new issue for the reminder

**Comment by ldemailly** [comment]
followup in https://github.com/istio/istio/issues/358
