### ISSUE TITLE
document automatic injection

### ISSUE THREAD

**Issue by ldemailly** [istio/pilot#1046]
Tracking issue to track documentation of automatic injection requirements and how to set it up
(will eventually also have a task/PR in the website)

**Comment by ayj** [comment]
Notes on environment setup / requirements (WIP):

## GKE

```bash
gcloud alpha container clusters create k0 \
  --enable-kubernetes-alpha \
  --cluster-version 1.7.3
```

## Minikube

* Use the latest version >= v0.21.0
* Use `--feature-gates=AllAlpha=true` *and* enable the `Initializers` admission plugin

```bash
minikube start \
    --extra-config=apiserver.Admission.PluginNames="NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,Initializers" \
    --feature-gates=AllAlpha=true \
    --kubernetes-version=v1.7.3
```

**Comment by linsun** [comment]
Add myself to add bluemix instructions for this.

**Comment by gyliu513** [comment]
I think the MiniKube and GKE documentation already been covered here https://github.com/istio/pilot/pull/1192

**Comment by ayj** [comment]
https://github.com/istio/pilot/blob/master/doc/testing.md includes steps to enable alpha features for initializer/webhooks.

https://github.com/istio/istio.github.io/pull/503 documents the overall usage of the initializer.

Anything else needed for this issue, or can we close it?

**Comment by andraxylia** [comment]
This is done.
