### ISSUE TITLE
Add support for building original_dst clusters

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/pilot#1050]
original_dst clusters were added in https://github.com/lyft/envoy/pull/1246.

Related to https://github.com/istio/istio/issues/496 .

**Comment by sakshigoel12** [comment]
Please update milestone

**Comment by sakshigoel12** [comment]
vadimeisenbergibm@ ETA

**Comment by vadimeisenbergibm** [comment]
Completed in 74b40c51fd0a54165d3771594ad99812304d653e
