### ISSUE TITLE
Use ConfigMap for sidecar initializer deployment configuration

### ISSUE THREAD

**Issue by ayj** [istio/pilot#1062]
The sidecar initializer is configured through command line flags. It might be nice to pull the configuration and sidecar template from a k8s ConfigMap (e.g. [envoy-initializer.yaml](https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/master/configmaps/envoy-initializer.yaml)). 

NOTE: The sidecar initializer and kube-inject currently share the same injection programmatic template. Adoption of [envoy-initializer.yaml](https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/master/configmaps/envoy-initializer.yaml) style template should ensure these templates don't diverge. kube-inject could use the newer k8s ConfigMap but care should be taken to avoid breaking offline mode, e.g. kube-inject might need to take ConfigMap YAML as argument to retrieve template.

**Comment by gyliu513** [comment]
I think that the injected configuration should be handled by pilot but not the configMap as the end user may update the configMap and caused the initializer does not work. @ayj

**Comment by ayj** [comment]
I'm not sure how pushing injection configuration into Pilot would solve that problem. The end user could make the same misconfiguration errors there. Ultimately the injection configuration should be protected and I believe that is possible today with appropriate RBAC settings on the ConfigMap.

Implemented by https://github.com/istio/pilot/pull/1104
