### ISSUE TITLE
sidecar command is not passed to pilot proxy command

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/pilot#1083]
According to 
https://github.com/istio/pilot/blob/master/platform/kube/inject/inject.go#L292, only `proxy -v2` arguments are passed to pilot, while it should be `proxy sidecar -v2`. Do I miss some initialization issues/compatibility issues? @kyessenov

**Comment by rshriram** [comment]
I think it's the default now.

**Comment by kyessenov** [comment]
that's probably a bug

**Comment by vadimeisenbergibm** [comment]
Fixed by https://github.com/istio/pilot/pull/1097.
