### ISSUE TITLE
Eliminate dependency from proxy on platform

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#1118]
Re: https://github.com/istio/pilot/commit/c54e6ec0a5cab3bce8b67af05b67d464422bcf65
We require that proxy does not depend directly on the platform. All interactions should go through the model abstraction, to decoupling the behavior from the environment. 
I'm not sure why the PR got merged as-is, please re-work it to avoid bundling platform with the proxy.

**Comment by kimikowang** [comment]
@GregHanson will solve this issue in his new PR, which is going to be pushed up soon.
