### ISSUE TITLE
Support merging registry data from k8s, consul, eureka

### ISSUE THREAD

**Issue by rshriram** [istio/pilot#1128]
Merge service registration data from different registries.
Simple assumptions (no service name collisions). 

This is essential if we want to demonstrate a consul cluster and k8s cluster (consul server running in k8s, consul agents in VMs/docker/CF/users periodically registering/heartbeating with Consul via Spring Cloud).

cc @kimikowang @GregHanson @ijsnellf

**Comment by ldemailly** [comment]
I agree we eventually should support merging (including for hybrid and multi cluster) but that's
out of scope for 0.2 no ? (it doesn't seem like we should add big features to 0.2 post code complete ?)
