### ISSUE TITLE
Remove `IstioNamespace` from core config metadata

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#1131]
This is against k8s standard metadata fields.
See https://github.com/istio/pilot/commit/720d751f5a82dcd746e3b36d8dadee96647c1d17#diff-2279f86634da3f787f279961af76713aR46

**Comment by andraxylia** [comment]
Can you send a reference or more details explaining the issue?

**Comment by ldemailly** [comment]
I think the idea is the only "namespace" we need is the watched namespace(s)

so it's the same issue as #1141 

I think we can live with whichever for 0.2 as long as it's clearly commented which is which
