### ISSUE TITLE
Use volume mount to propagate TLS key/cert to Ingress

### ISSUE THREAD

**Issue by myidpt** [istio/pilot#1134]
This is a security enhancement. Istio ingress should get the TLS cert/key for cluster-inbound traffic from a secure channel.

Currently, the flow of ingress TLS cert/key propagation is as follows:
The operator sets the TLS cert/key for ingress through a resource. Pilot reads the resource from apiserver, and exposes the cert/key through unsecure HTTP. Istio ingress's pilot-agent dynamically reads the HTTP endpoint and writes the TLS cert/key to the local file system for Envoy to consume.
(Tutorial: https://istio.io/docs/tasks/ingress.html#configuring-secure-ingress-https)

We plan to keep the same story for TLS cert/key propagation as how we propagate the in-cluster cert/key:
The operator sets the TLS cert/key for ingress through a secret. The secret is mounted as a volume when ingress starts. To support dynamically setting cert/key, Istio ingress's pilot-agent will restart Envoy when a new key/cert pair is set to the secret.

**Comment by kyessenov** [comment]
I think there's an extra step missing from explanation: the ingress controller reads a secret from ingress resource and then writes it to the special secret mounted on ingress proxy.

**Comment by myidpt** [comment]
Can the operator directly set the secret for the ingress controller, instead of creating a resource, and have the ingress controller convert to to a secret?

**Comment by ldemailly** [comment]
fix in istio/istio wasn't made correctly
