### ISSUE TITLE
CRD e2e pilot tests conflict among runs

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#1145]
W0830 18:02:23.383] ____Elapsed time: 70.669s, Critical Path: 62.52s
I0830 18:02:23.399] ==================== Test output for //adapter/config/crd:go_default_test:
I0830 18:02:23.399] --- FAIL: TestStoreInvariant (1.41s)
I0830 18:02:23.399] 	client_test.go:54: 5 errors occurred:
I0830 18:02:23.400] 		
I0830 18:02:23.400] 		* customresourcedefinitions.apiextensions.k8s.io "mock-configs.config.istio.io" already exists
I0830 18:02:23.400] 		* %!s(<nil>)
I0830 18:02:23.400] 		* %!s(<nil>)
I0830 18:02:23.400] 		* %!s(<nil>)
... skipping 16 lines ...
I0830 18:02:23.402] //platform/kube:go_default_test                                          PASSED in 0.9s
I0830 18:02:23.402] //platform/kube/inject:go_default_test                                   PASSED in 4.7s
I0830 18:02:23.402] //adapter/config/crd:go_default_test                                    TIMEOUT in 60.0s

**Comment by kyessenov** [comment]
This one-time change requires some hand-holding for the test cluster to get through smoothly.
