### ISSUE TITLE
Cannot have multiple cluster-wide installation with auth enabled

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#1154]
This does not apply to a production installation, where there is a single Istio installation, but to our testing cluster, where multiple test workloads are run concurrently. When test-infra will offer an isolated k8s cluster for each workload, this will no longer be an issue.

The issue is we cannot run multiple Istio-CA configured to listen to all namespaces, in the same cluster, because they will all be handled of all service accounts, and will race to generate secrets in all namespaces.

The solution for this case is to limit Istio-CA to one application namespace.

**Comment by ldemailly** [comment]
the same issue applies to mixer too I think (mixer listens to all namespaces)

**Comment by ayj** [comment]
We should retain `metav1.NamespaceAll` in addition to specific namespace (or set of namespaces). For reference, the sidecar initializer should handle this case (see
https://github.com/istio/pilot/blob/master/platform/kube/inject/initializer.go#L176)
