### ISSUE TITLE
Enable customize the initializer name

### ISSUE THREAD

**Issue by gyliu513** [istio/pilot#1169]
We are now hard coding the `side car initializer` as `sidecar.initializer.istio.io`, it is better that we can enable end user can customize it to a more meaningful name so that they can use this name for their `InitializerConfiguration`.

/cc @ayj I'd like to create a PR for this if you agree we can go ahead for this.

**Comment by ayj** [comment]
SGTM

**Comment by ldemailly** [comment]
I'm curious what is an example why one would need to change the name ? (isn't it arbitrary and istio specific/just need some name ?)

**Comment by ayj** [comment]
Multiple initializers running in the same cluster, i.e. our testing environment :)
