### ISSUE TITLE
go install in bin/init.sh in make setup fails on "unexpected directory layout" error

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/pilot#1177]
Maybe I miss something in my settings, however running `make setup` causes the following error for me:
```
unexpected directory layout:
	import path: github.com/golang/glog
	root: /home/vadime/go/src
	dir: /home/vadime/go/src/istio.io/pilot/vendor/github.com/golang/glog
	expand root: /home/vadime/go/src
	expand dir: /home/vadime/.cache/bazel/_bazel_vadime/e22facc439788d7baa501b1ad404ab5c/external/com_github_golang_glog
	separator: /
```

The problem is that vendorized `github.com/golang/glog` is symlinked to a directory `$HOME/.cache/bazel`. `go install` checks that the target of the symlink is outside of the parent directory and stops with an error. `go install` checks symlinks since the imported package is in `vendor` directory.

The relevant code in golang is here: https://github.com/golang/go/blob/5d39af9d9bac91b84b9944b1edffc6fb332747fa/src/cmd/go/internal/load/pkg.go#L513 .

**Comment by kyessenov** [comment]
I am not sure I understand the issue here. bazel_to_go script is mostly a hack to get linters understand bazel projects. It seems to work on the build machine with symlinks out of go source tree. Feel free to improve the script but `go install` is not supported for this project.

**Comment by vadimeisenbergibm** [comment]
@kyessenov Please note that `go install` is called by `bin/init.sh` - https://github.com/istio/pilot/blob/bd8370f437151b4dabe2d1b2ec1f4c7cca4dc7a4/bin/init.sh#L43

Could you please try to run `make setup` on your machine and see if `go install` succeeds? If it fails on your machine as well, I propose to remove it from the script. If it works on your machine, I wonder how it can work, since `go install` should not work with vendor directories that are symlinked outside of GOPATH.

**Comment by kyessenov** [comment]
If you want `make setup` be the source of truth for the build, then please update presubmit/test infra to use it. I recall now that `go install` is required for some of the linters to avoid spurious errors. Vendorizing symlinks has been working fine for almost a year, and is the tested method, so I suspect it's something with your development setup.

**Comment by ldemailly** [comment]
it only expends symlinks if the first check fails so maybe there is a bug in the first check

make setup works for me (and go install stage too) and is useful as it between other things put istioctl you just built into your path

try `bazel clean && rm -rf vendor/ && make setup`
and see if you still have the issue, if so reopen

**Comment by vadimeisenbergibm** [comment]
Resolved the issue by the following steps:

1. Removed previous go 1.6 and go 1.8 versions: `sudo apt-get remove golang-1.6` and `sudo rm -rf /usr/local/go`.
2. Installed the latest version of go -  `https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz`
3. Removed vendor dir, performed `bazel clean` and removed the bazel cache `~/.cache`
4. Ran `make setup` - everything worked

@kyessenov @ldemailly sorry for the confusion.
