### ISSUE TITLE
Envoy does not send to mixer target.service and target.uid is malformed

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#1185]
Right now, bookinfo with auth is broken. Accessing product page returns:

"RESOURCE_EXHAUSTED:Quota is exhausted for: RequestCount"

This is from mixer logs, caused likely by ingress Envoy not sending 

W0906 19:22:34.889646       1 <autogenerated>:6] default:error getting pod for (uid: kubernetes://.istio-system, key: istio-system/): pod 'istio-system/' does not exist

Logs here:
[targetdotservice.txt](https://github.com/istio/pilot/files/1282564/targetdotservice.txt)

Mixer also has to return a better error, this has nothing to do with quota @douglas-reid

**Comment by kyessenov** [comment]
What is the ingress pod template? It should have `POD_NAMESPACE` defined.

**Comment by andraxylia** [comment]
It does have POD_NAMESPACE, see below:
[ingress-pod.txt](https://github.com/istio/pilot/files/1282715/ingress-pod.txt)

I see in the logs the namespace is present, but name is missing. Shall I add POD_NAME?

**Comment by kyessenov** [comment]
Yes.

**Comment by andraxylia** [comment]
Fixed in istio/istio#696.
