### ISSUE TITLE
use mixer_check and mixer_report flags instead of mixer_control 

### ISSUE THREAD

**Issue by rshriram** [istio/pilot#1227]
We have a disable_policy_check field in the config that allows users to enable mixer for just reporting. However, Pilot does not honor this field currently. When its enabled, the opaque config generated for mixer in http should have `mixer_check: off` and `mixer_report: on`, and in the mixer filter's config [for both http and tcp], `disable_tcp_check_calls: true`.

**Comment by ldemailly** [comment]
the bug if any is the api SHA is from Aug 29 but we should stop adding new feature/requirements to 0.2 or any non critical changes

**Comment by rshriram** [comment]
This was added in order to let people use mixer's reporting system alone while disabling policy checks - otherwise we disable mixer completely. This was discussed extensively in the design doc. We have customers who would like to take advantage of Mixer's reports but are not willing to take the latency hit caused by checks. This is a deal breaker for them.
