### ISSUE TITLE
Unable to read code coverage report

### ISSUE THREAD

**Issue by sebastienvas** [istio/pilot#1267]
Here is an example of failure https://storage.googleapis.com/istio-prow/pull/istio_pilot/1266/pilot-coverage/153/build-log.txt

**Comment by kyessenov** [comment]
Coverage test needs access to a cluster.

**Comment by sebastienvas** [comment]
Really ?

**Comment by sebastienvas** [comment]
I guess we need to revert https://github.com/istio/pilot/commit/3284c3482331469ea59817a995477d40656dd21e

**Comment by kyessenov** [comment]
I see that I approved it sorry. That's my mistake, let me revert it.
