### ISSUE TITLE
postsubmit broken

### ISSUE THREAD

**Issue by sebastienvas** [istio/pilot#1281]
Note that postsubmit does not use bazel cache to catch this kind of issue before release.

Please check https://k8s-gubernator.appspot.com/build/istio-prow/pilot-postsubmit/172/

**Comment by xiaolanz** [comment]
I cannot repo the build failure locally.

**Comment by sebastienvas** [comment]
That s ok I have a fix for it, but for info you need to
git clean -xdf (do -n first)
rm your bazel cache ie output from
bazel info | grep output_base
bazel clean

I just added this to the oncall playbook.

**Comment by xiaolanz** [comment]
thanks for taking on this!
