### ISSUE TITLE
Pilot crashed with " fatal error: concurrent map read and map write" error

### ISSUE THREAD

**Issue by mclarke47** [istio/pilot#1377]
Stack trace can be found here:
https://gist.github.com/mclarke47/50ff5bcfaa89a0b067e3cc10d6a59fbd

Pilot seemed to crash causing the ingresses to not know where to route traffic resulting in lots of `404 NR` errors in the envoy access logs.

Version 0.2.6

Deploying the same as in the [sample](https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml).

As a side note, is pilot able to operate in a HA mode? So that further crashes can be mitigated.

**Comment by rkpagadala** [comment]
Multiple Pilot instances/replicas can be run at the same time, which mitigates the loss of one pilot crashing.

**Comment by mandarjog** [comment]
Concurrent access to the `podCache` @kyessenov, this a real bug, we need to fix it.

**Comment by rkpagadala** [comment]
Working on the fix

**Comment by linsun** [comment]
agree that this is critical for 0.2x
