### ISSUE TITLE
istioctl not defaulting ns to "default"

### ISSUE THREAD

**Issue by frankbu** [istio/pilot#1472]
Istioctl doesn't seem to be defaulting the namespace. For example:
```
$ cat <<EOF | istioctl create -f -
> apiVersion: config.istio.io/v1alpha2
> kind: RouteRule
> metadata:
>   name: maintenance-route
> spec:
>   destination:
>     name: maintenance
>   route:
>   - labels:
>       version: v1
>     weight: 100
> EOF
Error: an empty namespace may not be set during creation
```
It works if I add `-n default` to the command.

I'm pretty sure this used to work, but is no longer working in 0.2.7.

**Comment by linsun** [comment]
Would not this be based on your current kubectl context and the namespace for the current context?
