### ISSUE TITLE
istioctl CLI version subcommand should include information about the control plane version

### ISSUE THREAD

**Issue by esnible** [istio/pilot#293]
It is difficult for users to know if their third party resource exists and if their Istio control plane is running.

`istioctl version` should work like `kubectl version` and return similar information about the version of the Istio components running on the cluster manager.

**Comment by esnible** [comment]
On Slack, @kyessenov wrote https://istio-dev.slack.com/archives/manager/p1488826094005438
"regarding build information, we haven't wired it through (difficulty with bazel), but I agree we need version information"

**Comment by esnible** [comment]
See #169 for the version of the CLI appearing as a subcommand.

**Comment by esnible** [comment]
_istioctl_ doesn't have direct access to the control plane.  Currently the IstioConfig does not know what version of Istio is running.

`curl -k -XGET -H Accept: application/json, */* http://localhost:8080/apis/istio.io/v1alpha1/namespaces/default/istioconfigs` just gives the apiVersion, which is always istio.io/v1alpha1.  It would be nice if the config also received information about the version of the control plane implementation.

**Comment by esnible** [comment]
@liamawhite May I take this one over?  I am doing the server side as well.

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #3](https://github.com/istio/galley/issues/3) via [**ZenHub**](https://www.zenhub.com/)
