### ISSUE TITLE
Ensure that proxy injection + setup mechanism works for other proxies

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#39]
Our Envoy solution pulls lots of tricks (iptables, init containers) that are either not applicable to some deployments or not supported by other proxies.
We should make sure that we can support nginx, linkerd, etc by leaving all the customizations as pluggable hooks that third-party contributors can fill in. Ideally, the choice of a proxy mesh should be an implementation detail to the rest of Istio.

**Comment by rshriram** [comment]
Use of features like SO_ORIG_DST is highly dependent on the proxy. And our transparent proxying relies on the proxy being able to distinguish upstream connections based on this feature. So, there is nothing much we can do about this. Besides, Linkerd folks have demonstrated that Pilot can be integrated with proxies other than Envoy.

Closing for now.
