### ISSUE TITLE
Document routing rules in envoy config

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#427]
Document what each routing rule generates as config for envoy, so we can easily check the running envoy config and troubleshoot if routing behavior is not as expected.
#401

**Comment by ayj** [comment]
Is this issue still relevant? Most of the Envoy configuration is now distributed dynamically via xDS and the remaining static pieces should go away once envoy v2 API lands.

**Comment by kyessenov** [comment]
We'll need an issue for establishing causality throughout distribution to use, but that's after v2 lands.
