### ISSUE TITLE
Transparent mutual TLS auth setup conflicts with kubernetes health probes

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#479]
In case of mutual TLS enabled mesh, the health checker in k8s does not have a client-side proxy to initiate the TLS connection. That means the health probes initiated by kubelet will be sent as clear text to the proxy that expect an SSL connection.

Concretely, let's say my pod declared port 80, that is used by service port 80. I add a liveness probe on port 80, path /status. Proxy creates a TLS context on port 80.  Kubelet makes a request to port 80 path /status. Request doesn't go through the proxy since proxy expects SSL. Kubelet kills the pod.

**Comment by rshriram** [comment]
Doesn't the health check run within the pod? i.e. its container local traffic, such that it will not be captured by the proxy ?

**Comment by kyessenov** [comment]
AFAIK, it's node-to-pod traffic. The source is kubelet (node agent).

**Comment by myidpt** [comment]
Currently the SSL context is applied per IP+port, not path. IMO, there are three solutions:
1. Having Kubelet run behind a proxy. This might be the easiest but intrusive to K8s.
2. Modifying Envoy to apply SSL context on method/path level. This can be a long-term solution, but I think enabling per-method auth spec will potentially be meaningful in the long run.
3. Requiring the backend to export health status through a separate port. And Istio auth does not apply SSL context on that port (per-service auth spec is in our plan).

I didn't think thoroughly on these solutions, so please comment :) In any case, this bug will likely to be solved in beta or later.

**Comment by kyessenov** [comment]
2) Will not work since TLS encrypts the path. 1) is difficult to deploy on GKE. I think we should just go with 3). This needs to be documented for alpha, most deployments on k8s will have health probes.

**Comment by myidpt** [comment]
You are right that 2) will not work. 3) doesn't look like to offer good user experience for developers, but it seems to be the feasible one out of the three.

**Comment by wattli** [comment]
Vote for 3 too. Kuat, thanks for bringing this up.

**Comment by wattli** [comment]
@wlu2016 , FYI

**Comment by ayj** [comment]
Would server-side SNI in combination with setting host field in LivenessProbe's HTTPGetAction work?

Wouldn't #3 potentially require application to be re-written, i.e. istio-aware? Could we achieve a similar result by swapping out user-defined port with unused port (via admission controller) and forward traffic back to the originally port via envoy?

**Comment by wattli** [comment]
wencheng, yang, and I just had some discussion and here is the update:

For short term solution, we will let service open a dedicated port without SSL for health check (if applicable). And we will document it in our alpha release doc.

For long term solution, we can support server side TLS or mTLS ideally (by assigning client cert to kubelet).

**Comment by wattli** [comment]
We will use https://github.com/istio/auth/issues/262 to track this issue since it's on Auth team.
