### ISSUE TITLE
Istio mutual TLS auth and egress traffic

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#525]
There are two mechanisms that we are thinking to allow egress traffic:
1) external name service - appears like a regular k8s service but in fact sends traffic outside through a proxy
2) loose iptables traffic capture - allow any traffic outside as long as IP does not match pod or service IP masks

How does this work with mutual TLS enabled auth?

I think 1) should not be allowed just like we don't have ingress with in-cluster auth.
2) also sounds like a potential loophole.

**Comment by andraxylia** [comment]
#515 

Do we need a separate issue?

**Comment by kyessenov** [comment]
Auth effectively changes protocol at TCP level, so it's a separate concern. We can use this issue just for the auth-related problems.

**Comment by rshriram** [comment]
Superseded by egress rules.. and auth sorted out there.
