### ISSUE TITLE
e2e tests with pre-created k8s namespace fail

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#529]
This used to work, it could be related to auth.

bin/e2e.sh -debug -hub <> -tag <> -n <k8s-namespace>

**Comment by wattli** [comment]
Oliver, can you take a look please? I met the same issue today.

**Comment by wattli** [comment]
Andra, actually you can easily verify by turning off auth

bin/e2e.sh -debug -hub <> -tag <> -authmode disable -n

More detail:
https://github.com/istio/manager/blob/master/test/integration/driver.go#L114

**Comment by kyessenov** [comment]
we need to do a big refactoring of the test driver, can take a look at this. I think auth change requires two distinct namespaces.

**Comment by wattli** [comment]
What's the error you saw?
The auth is turned off by: " -auth disable".

**Comment by andraxylia** [comment]
I tried with -auth disable and it still fails. The error is:

I0414 11:07:11.380308  110542 driver.go:410] kubectl exec t-3079723187-vc9qr -n test3 -c app -- client -url https://istio-ingress-controller:443/b -insecure
I0414 11:07:12.166188  110542 driver.go:211] failed to inject proxy from t to a (url https://istio-ingress-controller:443/a)
I0414 11:07:12.166227  110542 driver.go:224] Cleaning up ingress secret.
I0414 11:07:12.166235  110542 driver.go:400] kubectl delete secret ingress -n test3
secret "ingress" deleted
ERROR: Non-zero return code '1' from command: Process exited with status 1.

@kyessenov Can you elaborate on the two distinct namespaces?

**Comment by kyessenov** [comment]
This is not supported anymore since the auth and non-auth tests cannot be run in the same namespace.

**Comment by kyessenov** [comment]
Tests run both auth and non-auth in a sequence. Assigning to you, it's fixable but it requires more work cleaning up after each test.

**Comment by kyessenov** [comment]
add @ldemailly since he hit this issue, too, and this needs to be resolved (closed or fixed)

**Comment by andraxylia** [comment]
e2e tests without auth work with pre-created namespace.
We should fix this, maybe add 2 more flags for the auth namespaces (with the cluster-wide change, there will be one namespace for istio and one for the app).

**Comment by ldemailly** [comment]
it worked for me with specifying the -auth flag (what didn't work was me mixing auth and non auth)

I think this is working / can be closed (or maybe with some --help addition?) ?
