### ISSUE TITLE
Traffic should be treated as in-cluster after being accepted by the Ingress

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#638]
Traffic should be treated as in-cluster after being accepted by the Ingress.
Ingress-proxy should talk with mixer.

**Comment by rshriram** [comment]
fixed by #1019

**Comment by andraxylia** [comment]
Clarification for the first part of this issue "Traffic should be treated as in-cluster after being accepted by the Ingress":
It is supported: ingress traffic to a URL is first mapped to the destination service:port based on the k8s ingress resource config, then it is subject to the Istio routing rules configured for that destination service.
