### ISSUE TITLE
Incorrect HTTP response from Istio Discovery Manager for invalid rule create and delete

### ISSUE THREAD

**Issue by esnible** [istio/pilot#648]
If the user does `istioctl delete route-rule not-a-real-rule-name` the CLI performs `DELETE http://localhost:8081/v1alpha1/config/route-rule/default/not-a-real-rule-name` and the Istio Discovery Manager returns HTTP 500 status indicating a server error.

It should return 404.

If the user tries to create rules that already exists the CLI does `POST http://localhost:8081/v1alpha1/config/route-rule/default/reviews-default` and the server responds with 500.  It should respond with 403 Forbidden.

**Comment by liamawhite** [comment]
I'm investigating now but the second one is supposed to return 409 conflict. I'm open to reasons for returning 403 though...

**Comment by esnible** [comment]
@liamawhite I can live with 409.  Let me explain why I expected 403 however.  I consider it invalid to POST something new where something already exists.  The 409 conflict is something I associate with a merge conflict.  For example, when posting to Cloudant you POST to https://$USERNAME.cloudant.com/$DATABASE and it gives back JSON with a _id_ and a _rev_.  The base URL and the ID make a new URL.  If two peers try to GET https://$USERNAME.cloudant.com/$DATABASE/$id, modify, and PUT the first client has success.  The second one had an old _rev_ and gets a 409 and can try to GET/modify/PUT again.

Istio isn't expecting multiple users to PUT conflicting changes to rules so we don't bother with trying to detect that.  The multiple writers problem is what I usually associate with 409.

**Comment by esnible** [comment]
I am getting 500 "2 errors occurred:\n\n* weight must be in range 0..100\n* Route weights total 999 (must total 100)"

These errors are not server errors.  The client sent invalid data.  The server should return 400.

**Comment by liamawhite** [comment]
@esnible I'll take a look at this now. We need more error typing from the registry though.

**Comment by esnible** [comment]
@liamawhite Now that there are REST tests for _apiserver_ in _istio/manager/test/integration/apiserver.go_ this work should be unblocked.  I have been `go build`-ing the _integration_ directory and  using `./test/integration/integration --tag $MANAGER_TAG -hub $MANAGER_HUB --testtype "apiserver" --auth disable --count 3` to test.  It's pretty quick.

**Comment by liamawhite** [comment]
I will take a look at this when I can actually get a working dev environment.

**Comment by ijsnellf** [comment]
I'm going to weigh in favor of 409 rather than 403.

From RFC:
> 10.4.4 403 Forbidden
>
> The server understood the request, but is refusing to fulfill it. **Authorization will not help and the request SHOULD NOT be repeated.** If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead. 
>
> ....
>
> 10.4.10 409 Conflict
>
> **The request could not be completed due to a conflict with the current state of the resource.** This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request. The response body SHOULD include enough information for the user to recognize the source of the conflict. Ideally, the response entity would include enough information for the user or user agent to fix the problem; however, that might not be possible and is not required.

The server can't fulfill the request because it is an invalid state change for the resource ("create" on something that already exists). It doesn't have anything to do with privileges or authorization.

http://stackoverflow.com/questions/25541203/http-response-code-when-resource-creation-post-fails-due-to-existing-matching-re

**Comment by esnible** [comment]
@ijsnellf Some of the confusion is due to how we create.  We create using /v1alpha1/config/route-rule/default/name yet the body ALSO contains a name.  (And it doesn't have to match!!!)  Most HTTP CRUD services expect to POST to the parent, in our case, /v1alpha1/config/route-rule/default.  Although I prefer 403 for creation failure I agree that 409 is just as good if we continue to allow POSTing to the URL we want for the rule rather than to its parent.

**Comment by kyessenov** [comment]
We're reconsidering how to clean up the URI scheme here https://github.com/istio/api/issues/94

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #26](https://github.com/istio/galley/issues/26) via [**ZenHub**](https://www.zenhub.com/)
