### ISSUE TITLE
kube-inject support for debug images

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#666]
Add a flag --debug for kube-inject so the resulting injected proxy and init use the debug baseline image.

**Comment by andraxylia** [comment]
Partialy fixed in istio/manager#702 for alpha, moving to beta to add the flag.

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #13](https://github.com/istio/galley/issues/13) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ldemailly** [comment]
Subscribe
