### ISSUE TITLE
istioctl confusing error message when creating rules in non-default namespace

### ISSUE THREAD

**Issue by esnible** [istio/pilot#704]
The current error message is confusing:

```
istioctl --namespace abc create -f ../istio/demos/apps/bookinfo/route-rule-all-v1.yaml 
Error: the server could not find the requested resource
```

The user was supposed to supply `--istioNamespace=default`

_istioctl_ is getting a message from Kubernetes, a JSON-wrapped message of "services \"istio-manager\" not found".  Even that would be better than what we have now.

Ideally _istioctl_ could understand the message is coming from Kubernetes because there is no istio-manager Service in the "abc" namespace and suggest the user use --istioNamespace` in addition to --namespace.

**Comment by ayj** [comment]
> From https://istio.io/docs/tasks/installing-istio.html#installation-steps 
> 
> For the 0.1 release, Istio must be installed in the same Kubernetes namespace as the applications.

The error message should only be seen if user installs Istio in a different namespace than the applications.

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #11](https://github.com/istio/galley/issues/11) via [**ZenHub**](https://www.zenhub.com/)
