### ISSUE TITLE
Ingress with NodePort and firewall no longer gets IP address

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#707]
Behaviour used to be similar to #635 , with multiple IP addresses being displayed, but right now, the field remains empty.

**Comment by kyessenov** [comment]
@andraxylia this is the wrong repo. file a bug against kubernetes/ingress

**Comment by andraxylia** [comment]
Let's first make sure k8s is at fault.

**Comment by kyessenov** [comment]
https://github.com/istio/manager/blob/master/platform/kube/ingressstatus.go#L72
we're simply invoking the library to publish istio-ingress.

**Comment by ijsnellf** [comment]
What environment? GKE or minikube?

**Comment by andraxylia** [comment]
Fixed by istio/pilot#951
