### ISSUE TITLE
ambiguous istioctl commands (istioctl mixer rule create and istioctl create)

### ISSUE THREAD

**Issue by rshriram** [istio/pilot#710]
Istioctl mixer commands use explicit verbs and resource names in the command line, resulting in both longer command lines and ambiguous command set.. The commands for route rules are
`istioctl create|get|replace|delete -f <filename>`
while the commands for mixer are
`istioctl mixer rule create|get`. There is no istioctl mixer rule replace|delete.

The documentation and usage is pretty confusing. The two formats need to be unified into something like
`istioctl create|get|replace|delete -f <filename>`, where the type of the command, resource, etc. can be specified as part of the YAML file. for example

```bash
cat <<EOF | istioctl create
type: mixer-rule
name: ratelimit
spec:
 rules:
 - aspects:
   - kind: quotas
     params:
       quotas:
       - descriptorName: RequestCount
         maxAmount: 5
         expiration: 1s
EOF
```

The command structure and documentation of istioctl command is not cohesive. Its messy at the moment. Istioctl replace follows istioctl mixer rule.

Need to fix this before final release.

Ccing folks who worked on istioctl. @esnible @mandarjog @ayj 
cc @geeknoid

**Comment by ayj** [comment]
I already created https://github.com/istio/manager/issues/649 to track this issue but it was targeted for beta.

**Comment by kyessenov** [comment]
This is what mixer gives to us.

**Comment by kyessenov** [comment]
The work has to start from making changes to mixer to organize the configs. The hacky solution is to parse YAMLs in apiserver and dispatch them to mixer config server after rewriting URLs and content.

**Comment by ayj** [comment]
We can hack istioctl to use common top-level verbs but the specific syntax is likely to change in beta as we straightout the config API and server story.

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #10](https://github.com/istio/galley/issues/10) via [**ZenHub**](https://www.zenhub.com/)
