### ISSUE TITLE
Add version checks to API/Config server

### ISSUE THREAD

**Issue by ayj** [istio/pilot#715]
Istio Config server (manager/mixer) should have version check for backwards incompatibility with older versions of pre-alpha/alpha istioctl. Longer term (beta/post-beta) the API and config server should maintain backwards compatibility and/or fail gracefully.

**Comment by ayj** [comment]
From https://github.com/istio/manager/issues/722

> hackathon feedback:
> 
> gcloud (and other command line tools) check if a newer version is available. This would be very useful from a user experience standpoint.

> More importantly, istioctl should negotiate a version with the remote in-cluster apiserver.

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #9](https://github.com/istio/galley/issues/9) via [**ZenHub**](https://www.zenhub.com/)
