### ISSUE TITLE
Enable istioctl to work with helm chart release

### ISSUE THREAD

**Issue by dcberg** [istio/pilot#816]
We now have a helm chart for istio. When. you install istio via helm you can name the release used to install istio (or one is generated randomly). The helm release name is prefixed onto every kubernetes resource that is created. Thus if you installed helm using a release name of **foo** then. the manager service will be named **foo-istio-manager**. When this happens all `istioctl` commands will fail. The problem is that `istioctl` by default looks for **istio-manager** for the manager service name.

The only way to get around this problem today is to use the **managerAPIService** flag. Thus with our example above we have `istioctl --managerAPIService foo-istio-manager:8081`. This works but is not a pleasant user experience. 

Please make it easier to supply the istio manager service name (e.g., env variable).

**Comment by kyessenov** [comment]
Thanks. Yes, we'll tackle this as part of cluster-level installation probably.

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #6](https://github.com/istio/galley/issues/6) via [**ZenHub**](https://www.zenhub.com/)
