### ISSUE TITLE
Move from TPR to different backend for Istio rules backend

### ISSUE THREAD

**Issue by rshriram** [istio/pilot#819]
TPRs have proved to be unstable and are also hindering adoption in older k8s versions.

Like the mixer, its more portable to use something like redis to store Istio rules. Preferably, we could normalize the interface such that different backends can be plugged in. This would help platform portability as well.

cc @GregHanson @kyessenov @ijsnellf

**Comment by kyessenov** [comment]
cc @andraxylia who will need to create a persistent HA deployment of redis

**Comment by andraxylia** [comment]
We will tie this with the config server work. The choice of backend has not happened yet.

**Comment by kyessenov** [comment]
issue reassigned to galley.
TPR deprecation is in #848
