### ISSUE TITLE
Access to the Istio API/Configuration server is not protected. 

### ISSUE THREAD

**Issue by ayj** [istio/pilot#840]
Istio API/Configuration server does not have support for auth. Any pod/service with network access can create/modify/delete rules. Ideally we might want to support RBAC but initially it would be good to have basic cert/oauth support.

**Comment by kyessenov** [comment]
@lookuptable do we have a design for control plane auth and bootstrapping control plane identities?

**Comment by ldemailly** [comment]
Not just pilot but mixer too

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #5](https://github.com/istio/galley/issues/5) via [**ZenHub**](https://www.zenhub.com/)
