### ISSUE TITLE
istioctl should default to namespace of current context

### ISSUE THREAD

**Issue by esnible** [istio/pilot#858]
_istioctl_ defaults `--namespace` to k8s.io/client-go/pkg/api.NamespaceDefault which is the constant "default".

_istioctl_ SHOULD use the namespace from the _kubectl_ context.  This is the namespace you see when you do `kubectl config view --output jsonpath='{.contexts[?(@.name == "'$(kubectl config current-context)'")]..namespace}'`

Otherwise a user who is using a namespace other than default must do `--namespace XYX` on every operation.

**Comment by kyessenov** [comment]
please refile to https://github.com/istio/galley, which is the new home for istioctl

**Comment by kyessenov** [comment]
Issue moved to [istio/galley #4](https://github.com/istio/galley/issues/4) via [**ZenHub**](https://www.zenhub.com/)
