### ISSUE TITLE
Rule validation (abort 0% crashes envoy)

### ISSUE THREAD

**Issue by esnible** [istio/pilot#866]
If I create a rule like this:

```
destination: ratings.default.svc.cluster.local
httpFault:
  abort:
    httpStatus: 500
```

Then Envoy will fail with 

```
[critical][main] error initializing configuration '/etc/envoy/envoy-rev0.json': fault filter must have at least abort or delay specified in the config.
```

According to _istio/api/proxy/v1/config/http_fault.proto_:92 the percentage of requests to abort can be in the range 0-100.  If that claim is true the code that generates the Envoy configuration needs to special-case 0% and suppress creating the fault.  If that claim is false and Istio only supports the range 1-100 then the rule validation should be improved.

Note that a rules like

```
destination: ratings.default.svc.cluster.local
httpFault: {}
```
and

```
destination: ratings.default.svc.cluster.local
```

induce a similar crash.

**Comment by kyessenov** [comment]
Thanks for catching this!
