### ISSUE TITLE
pilot jenkins code coverage in presubmit takes 9 minutes

### ISSUE THREAD

**Issue by ldemailly** [istio/pilot#876]
pilot jenkins code coverage in presubmit takes 9 minutes

mandar said for mixer splitting -race and coverage in 2 jobs made the sum faster

kuat said it takes 30s on his machine

we should try to break down so we know how the time is spent ?

![screen shot 2017-06-15 at 3 31 54 pm](https://user-images.githubusercontent.com/3664595/27204394-d16e461e-51df-11e7-9fee-b9ce8096db13.png)

**Comment by sebastienvas** [comment]
@nlandolfi already split the code coverage to another job in Prow. So I ll just assign to him.

**Comment by sebastienvas** [comment]
Why did you close it ?

**Comment by sebastienvas** [comment]
we ll fix it once Prow is in use.

**Comment by kyessenov** [comment]
#878 fixed it by removing the race test
