### ISSUE TITLE
Invalid link in doc

### ISSUE THREAD

**Issue by ihac** [istio/pilot#881]
Hi, I was reading [_Istio Pilot design overview_](https://github.com/istio/pilot/blob/master/doc/design.md). Seems that the second link in `Configuration model` chapter is invalid now. The schema file has already been removed in `istio/api`([commit](https://github.com/istio/api/commit/6339e49e78b7b04aa5141e2594f5c4120f93c710)).

BTW, is there any up-to-date doc specifying how to configure routing rules?

Thanks.

Xiao An

**Comment by kyessenov** [comment]
The rules protobuf specification is still around, it just got moved to the website:
https://istio.io/docs/reference/config/traffic-rules/routing-rules.html
