### ISSUE TITLE
Istio route rules `match` criteria not respected for ingress traffic

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#895]
@kalantar commented on [Wed Jun 21 2017](https://github.com/istio/issues/issues/38)

I created a service that selects among 2 deployments (different versions).
I created two istio route-rules.
The first defaults all traffic to v1.
The second sends requests that have a particular header to v2.
I then deployed the sleep sample so that I could test these rules from inside the cluster. I found that both rules worked as expected.
I then created an ingress so that I could initiate requests from outside the cluster.
When I tested it by sending requests from outside the cluster, I found that the default rule was applied to every request, including those that match the second rule.
Note that I am doing this in a non default namespace. However, this does not seem to be the issue, see also: https://groups.google.com/forum/#!topic/istio-users/yQEogcx2hJM

Here are the rules: 

    $ more *rule*
    ::::::::::::::
    default-route-rule.yml
    ::::::::::::::
    type: route-rule
    name: default-route
    namespace: user-kalantar
    spec:
      destination: echo.user-kalantar.svc.cluster.local
      precedence: 1
      route:
      - tags:
          version: one
        weight: 100
    ::::::::::::::
    user-route-rule.yml
    ::::::::::::::
    type: route-rule
    name: echo-user-rule
    namespace: user-kalantar
    spec:
      destination: echo.user-kalantar.svc.cluster.local
      precedence: 2
      match:
        httpHeaders:
          x-user:
            exact: test
      route:
      - tags:
          version: two

The ingress is: 

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: echo-ingress
      namespace: user-kalantar
      annotations:
        kubernetes.io/ingress.class: istio
    spec:
      backend:
        serviceName: echo
        servicePort: 80

---

@ijsnellf commented on [Wed Jun 21 2017](https://github.com/istio/issues/issues/38#issuecomment-310163784)

@kyessenov, could you take a look at this? You are better acquainted with ingress route rules and their limitations.

---

@frankbu commented on [Wed Jun 21 2017](https://github.com/istio/issues/issues/38#issuecomment-310167790)

To reproduce:
```
$ kubectl apply -f <(istioctl kube-inject -f samples/apps/helloworld/helloworld.yaml)

$ cat <<EOF | istioctl create
type: route-rule
name: hello-default
spec:
  destination: helloworld.default.svc.cluster.local
  route:
  - tags:
      version: v1
EOF

$ cat <<EOF | istioctl create
type: route-rule
name: hello-canary
spec:
  destination: helloworld.default.svc.cluster.local
  precedence: 2
  match:
    httpHeaders:
      foo:
        exact: bar
  route:
  - tags:
      version: v2
EOF

$ export HELLOWORLD_URL=$(kubectl get po -l istio=ingress -o 'jsonpath={.items[0].status.hostIP}'):$(kubectl get svc istio-ingress -o 'jsonpath={.spec.ports[0].nodePort}')

$ curl -H "foo: bar" http://$HELLOWORLD_URL/hello # always returns v1
Hello version: v1, instance: helloworld-v1-1286076397-2nrdg
```

**Comment by kyessenov** [comment]
There is a limitation on combining match expressions coming route rules and ingress rules but this might not be it. I'll try to run the config gen logic on the input once I get time. Thanks!

**Comment by ceastman-ibm** [comment]
is it due to the difference in precedence?

**Comment by ceastman-ibm** [comment]
i have the following route rule and it seems to work externally:

type: route-rule
name: maintenance-info-default
spec:
  destination: maintenance-info.red.svc.cluster.local
  precedence: 1
  rewrite:
    uri: /
  route:
  - tags:
      version: red
    weight: 50
  - tags:
      version: black
    weight: 50

**Comment by frankbu** [comment]
Haven't gotten to the bottom of it yet, but I think it's the `match` part that's not working

**Comment by ceastman-ibm** [comment]
@frankbu yes it does appear to be an issue with the matching. i created a new route rule for a different microservice:

type: route-rule
name: common-default
spec:
  destination: common.red.svc.cluster.local
  precedence: 1
  match:
    httpHeaders:
      uri:
        prefix: "/common/"
  rewrite:
    uri: /
  route:
  - tags:
      version: red
    weight: 0
  - tags:
      version: black
    weight: 100

and what appears to happen is the following:

http://<ingress ip>/common/api/files returns a 404
http://<ingress ip>/api/files returns a 200 with the expected files

/common and /api are defined in the ingress to point to the same service

**Comment by rshriram** [comment]
fixed by #897

**Comment by nmnellis** [comment]
I am running istio 0.4.0 and we are noticing this exact behavior. Though some of the route rules will work for a while(until another update is made) and then they wont work anymore and others will work. We are only noticing this issue with ingress controller. sidecars do not appear to have this issue.

example ingress
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: app1-ingress
  namespace: ns1
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: app1
          servicePort: 80
        path: /app1/.*
```
Example route rule
```yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: app1
  namespace: ns1
spec:
  destination:
    name: app1
  match:
    request:
      headers:
        uri:
          prefix: /app1/
  rewrite:
    uri: /  
```
response from app1 `http://example.com/app1/info` .. we should have gotten the infor response not 404
```json
{
"timestamp": 1517495357726,
"status": 404,
"error": "Not Found",
"message": "No message available",
"path": "/app1/info"
}
```
Ingress /routes response
```json
{
	"version_info": "hash_5652f7f64d6507e2",
	"route_config_name": "80",
	"cluster_name": "rds",
	"route_table_dump": {
		"name": "80",
		"virtual_hosts": [{
			"name": "example.com",
			"domains": ["example.com", "example.com:80"],
			"routes": [ {
				"match": {
					"prefix": "/app1/"
				},
				"route": {
					"cluster": "out.app1.ns1.svc.cluster.local|http",
					"timeout": "0s"
				},
				"metadata": {
					"filter_metadata": {
						"envoy.router": {
							"destination.service": "app1.ns1.svc.cluster.local",
							"mixer_check": "on",
							"mixer_report": "on",
							"mixer_forward": "on"
						}
					}
				},
				"decorator": {
					"operation": "default-route"
				}
			}, {
				"match": {
					"prefix": "/app1/"
				},
				"route": {
					"cluster": "out.app1.ns1.svc.cluster.local|http",
					"prefix_rewrite": "/",
					"timeout": "0s"
				},
				"metadata": {
					"filter_metadata": {
						"envoy.router": {
							"destination.service": "app1.ns1.svc.cluster.local",
							"mixer_check": "on",
							"mixer_report": "on",
							"mixer_forward": "on"
						}
					}
				},
				"decorator": {
					"operation": "app1"
				}
			}]
		}]
	}
}
```

**Comment by frankbu** [comment]
@nmnellis Your problem sounds like a new issue. This one was a simple bug in the the ingress controller where route rule `match` was always failing at ingress. I'd suggest opening a new issue, since this one is closed and won't get anybody's attention.
