### ISSUE TITLE
Our JSON definition of load balancing weight is incorrect

### ISSUE THREAD

**Issue by esnible** [istio/pilot#898]
I don't believe load balancing weights are implemented in Istio, but the data structure in _discovery.go_ does not match Envoy.

Istio will serialize the weight as a peer to the IP address (following https://github.com/istio/pilot/blob/master/proxy/envoy/discovery.go#L156 ) but the Envoy documentation says the weight goes under _tags_.

https://lyft.github.io/envoy/docs/configuration/cluster_manager/sds_api.html#config-cluster-manager-sds-api

**Comment by ijsnellf** [comment]
@esnible: Do you have a scenario where weighted routing does not work? We have automated tests for weighted routing. I agree there may be a mismatch, but I don't think it is causing undesirable behavior. I don't think the weight from SD is being used.
