### ISSUE TITLE
Allow users to customize template used for kube-inject

### ISSUE THREAD

**Issue by frankbu** [istio/pilot#899]
Related discussion: https://groups.google.com/forum/#!topic/istio-users/VPCkOuxiu10

This would be also be useful for enabling autoscalers if we don't fix #608

**Comment by ldemailly** [comment]
also why is the current image pull policy Always ? (the answer is not because that's what's in the file - I'm asking why is it Always in the file - given we use unique tags for everything ?)

**Comment by cmluciano** [comment]
Do we want to consider a config-map instead of a file?

**Comment by ayj** [comment]
[kubernetes-initializer-tutorial](https://github.com/kelseyhightower/kubernetes-initializer-tutorial) uses a configmap for template configuration (see [here](https://github.com/kelseyhightower/kubernetes-initializer-tutorial/blob/master/configmaps/envoy-initializer.yaml)). The first iteration of our initializer will use the existing kube-inject hardcoded template to maintain parity with the existing manual injection method. We can migrate to customizable templates via ConfigMap after the initializer is stabilized and the manual method is deprecated.

**Comment by cmluciano** [comment]
roger that, is there an issue that I could reference as a dependency in zenhub?

**Comment by ayj** [comment]
https://github.com/istio/pilot/issues/1062 should address this problem

**Comment by ldemailly** [comment]
this was 0.2 while #1062 is 0.3... is that ok ?

**Comment by ayj** [comment]
SGTM so long as its P1/P2
