### ISSUE TITLE
File system config adapter

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#924]
Provide an alternative file system based backend as a temporary solution for VM work.
This work will likely be superseded by one Galley adaptor to replace both FS and TPR adapters.

1. File system store.
Implement route rule representation as files in a directory hierarchy.

2. inotify watcher.
Implement config change watcher using inotify.

cc @gnirodi @costinm @rshriram @mandarjog

**Comment by ldemailly** [comment]
subscribe

**Comment by kyessenov** [comment]
closing as we're focusing on CRD backend first.
