### ISSUE TITLE
Istioctl kube-inject fails to validate config map

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#935]
Kube-inject is not working in latest master, it complains about not finding the config map, but the map is there, it is the validation that fails.

$ istioctl kube-inject -f samples/apps/bookinfo/bookinfo.yaml -v 10
I0718 13:29:16.027956   21258 loader.go:354] Config loaded from file /usr/local/google/home/andracis/.kube/config
I0718 13:29:16.029744   21258 round_trippers.go:398] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: istioctl/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Basic YWRtaW46UXBsdHVPN0E4U29VT2F0Vg==" https://35.197.13.236/api/v1/namespaces/default/configmaps/istio
I0718 13:29:16.165889   21258 round_trippers.go:417] GET https://35.197.13.236/api/v1/namespaces/default/configmaps/istio 200 OK in 136 milliseconds
I0718 13:29:16.165918   21258 round_trippers.go:423] Response Headers:
I0718 13:29:16.165931   21258 round_trippers.go:426]     Content-Type: application/json
I0718 13:29:16.165941   21258 round_trippers.go:426]     Content-Length: 537
I0718 13:29:16.165951   21258 round_trippers.go:426]     Date: Tue, 18 Jul 2017 20:29:16 GMT
I0718 13:29:16.166004   21258 request.go:991] Response Body: {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"istio","namespace":"default","selfLink":"/api/v1/namespaces/default/configmaps/istio","uid":"75b97d6e-6bea-11e7-884f-42010a8a01ba","resourceVersion":"8657121","creationTimestamp":"2017-07-18T18:53:59Z"},"data":{"mesh":"# Uncomment the following line to enable mutual TLS between proxies\n# authPolicy: MUTUAL_TLS\nmixerAddress: istio-mixer:9091\ndiscoveryAddress: istio-pilot:8080\ningressService: istio-ingress\nstatsdUdpAddress: istio-mixer:9125\nzipkinAddress: zipkin:9411"}}
Error: Istio configuration not found. Verify istio configmap is installed in namespace "default" with `kubectl get -n default configmap istio`

$ kubectl get -n default configmap istio
NAME      DATA      AGE
istio     1         2h

**Comment by mwieczorek** [comment]
@andraxylia any workaround for this?

**Comment by andraxylia** [comment]
The master is still broken, even if some fixes went in, this is the current issue.
istio/pilot#971

The workaround is to supply --hub and --tag to istioctl:

. istio.VERSION
wget $ISTIOCTL_URL/istioctl-osx
mv istioctl-osx istioctl
chmod a+x istioctl
kubectl apply -f install/kubernetes/istio.yaml
kubectl apply -f <(./istioctl kube-inject -f samples/apps/bookinfo/bookinfo.yaml --hub $PILOT_HUB --tag $PILOT_TAG)

I tried with this SHA sourced from current istio.VERSION:

wget https://storage.googleapis.com/istio-artifacts/pilot/5633d45a99138892a0ba0d380dff5c587583edd3/artifacts/istioctl/istioctl-osx

k apply -f <(./istioctl kube-inject -f samples/apps/bookinfo/bookinfo.yaml --hub gcr.io/istio-testing --tag 5633d45a99138892a0ba0d380dff5c587583edd3 --namespace default)

**Comment by ldemailly** [comment]
should be working in 0.2.0 (but not on mac, https://github.com/istio/istio/issues/544)

it may/may not be working with custom / local builds or sourcing istio.VERSION (not sure we support that anymore, we wanted to get away from sourcing istio.VERSION afaik)

please reopen or file a specific issue if something is still not working
