### ISSUE TITLE
mount mesh config (from ConfigMap) as a file in sidecars

### ISSUE THREAD

**Issue by rshriram** [istio/pilot#945]
With the introduction of LDS support ( #934 ), we no longer need to query K8S api from the proxy agent for configuring Envoy. The only dependency is the mesh configuration, that is provided as a config map today.

Need to change our deployment configs (in istio/istio) and the tests to mount the config map as a file, and change the proxy agent code to read the mesh config from the file. This would greatly reduce the size of the proxy agent binary, plus make it more portable across non k8s environments.

**Comment by ldemailly** [comment]
cc @costinm
