### ISSUE TITLE
istioctl kube-inject is broken in master(0.2)

### ISSUE THREAD

**Issue by andraxylia** [istio/pilot#971]
istioctl kube-inject called without parameters injects by default a proxy with tag 0.1.

This is now broken in istio/istio master, because the pilot agent has recently changed to no longer take the sidecar parameter.

The fix is to change kube-inject to read the hub and tag from the istio config map.

This requires a corresponding fix in istio/istio to change the config map.

**Comment by ldemailly** [comment]
I thought I had filled that already but can't find it:
we need to make sure the proxy tag has 3 digits and not 2 so pushing a new one doesn't insta change/break earlier releases

also be extra careful to not modify the 0.1 (0.1.6) image

**Comment by kyessenov** [comment]
this is again a problem with two repos. istioctl is built in pilot but needs to use istio.VERSION in istio/istio.

**Comment by ayj** [comment]
https://github.com/istio/pilot/issues/568

cc @sebastienvas - I recall we used 2 digits (no patch) to avoid having to rebuilt istioctl for each version. At the time it made sense, but in practice we haven't made that many patch releases.

**Comment by andraxylia** [comment]
It does not use or need to use istio.VERSION.

Right now, the pilot e2e tests pass because they pass hub and tag to istioctl kube-inject, which override the values read from the configmap.

The PR will be first in pilot, then in istio.

**Comment by kyessenov** [comment]
istio.VERSION defines the release target version that needs to be passed to already-compiled istioctl. This is due to backwards build process that we have.

**Comment by sebastienvas** [comment]
There was no 0.2 release yet, so I am assuming what Jason is saying is correct. We probabaly going to make a release this week to make sure we still can.

**Comment by ldemailly** [comment]
this should work in 0.2.0 (reopen if not)
