### ISSUE TITLE
updating to client-go 1.7 breaks kube-inject

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#975]
Due to a custom serializer in k8s, PR #966 breaks k8s 1.6 deployment:
```
error: error validating "STDIN": error validating data: found invalid field sizeLimit for v1.EmptyDirVolumeSource; if you choose to ignore these errors, turn validation off with --validate=false
```

@ayj proposed several options around this problem:
- custom YAML/JSON marshaler
- textual removal post-encoding
- programmatic removal
  - convert typed resource to generic map[string]interface{} (https://github.com/fatih/structs)
  - remove offending key(s)
  - marshal generic map to YAML

Also filed upstream issue https://github.com/kubernetes/client-go/issues/257

cc @rshriram

**Comment by kyessenov** [comment]
@andraxylia @ayj the response I got is that client-go is not meant to be backwards compatible with older k8s. We might need to reimplement kube-inject.

**Comment by kyessenov** [comment]
Priority depends on whether we want to support k8s 1.6 server _at all_.

**Comment by andraxylia** [comment]
We will not support k8s < 1.7 because of the CRDs, so I will close this issue.
